/* Q5) You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"

Output: "e" */

let s = "abcd"
let t = "abcdef"

for (let i = 0; i < t.length; i++) {
    if (!s.includes(t[i])) {
        console.log(t[i])
        break
    }
}